title: Anna Le
email: annale3898@gmail.com
description: >-
  BSc Honours Computer Science student at UCalgary. 
  Former SDE Intern at AWS & Identity Developer at AER.
baseurl: "" 
url: "https://annaisjoy.github.io"
github_username: annaisjoy

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - index.md
